# Generated by Django 5.1.3 on 2024-11-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_decorators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
